### PR TITLE
Fix empty portfolio when user has multiple accounts

### PR DESCRIPTION
**Pull request by junyuanz1**
Problem:
- when the user has multiple accounts, the portfolio returned by ib_insync will be an empty array

Solution:
- always pass account id to different methods

### CODE REVIEW

**Comment by petebra11** [comment]
Running into this issue with multiple accounts under one login, where "Portfolio positions: " doesn't populate, but "Account Summary: " values are getting pulled correctly in the output. 

tailing ib_insync logs shows all positions are getting called (strangely no account summary details here), yet none of my accounts will work. Paper account worked flawlessly since there wasn't multiple account numbers in position summary.

**Comment by brndnmtthws** [comment]
> 

Odd, you could try modifying the code and experimenting with the account APIs. Maybe try printing the output [from this call with](https://ib-insync.readthedocs.io/api.html#ib_insync.ib.IB.managedAccounts) `print(self.ib.managedAccounts())` and make sure the account details match what you expect.

**Comment by petebra11** [comment]
output of `ib.managedAccounts()` is what I expect. Are there more in-depth ways I can log this? Seems weird it pulls NLV/buying power/etc. correctly but not positions.

**Comment by petebra11** [comment]
Not sure what changed, but thetagang 1.6.0 is now working with multiple accounts.

**Pull request merged**
