### PR TITLE
Don't blow up if fields are missing

### PR DESCRIPTION
**Pull request by brndnmtthws**
Sometimes we don't have data (i.e., no bids/asks, no market price) for contracts, and rather than blowing up we should just continue gracefully

FYI @junyuanz1

### CODE REVIEW

**Comment by brndnmtthws** [comment]
I'm not 100% sure this is the desired behaviour, I need to understand some of the changes from #521 a little better. I think in some cases it might be better to go through the path above this exception (i.e., in case it's better to close the contract).

**Comment by junyuanz1** [comment]
so in this code block, there are several potential calls that could cause this problem:

```
buy_ticker = await self.ibkr.get_ticker_for_contract(position.contract) (requires market price)

await self.put_is_itm(position.contract) (requires market price)

sell_ticker = await self.find_eligible_contracts(...) (required market price for the symbol, no required field for option contracts)

maximum_new_contracts = await self.get_maximum_new_contracts_for (requires market price)
```

My assumption was `marketPrice` is the less restricted data points according to the `ib_async` code:

```
if self.hasBidAsk():
    if self.bid <= self.last <= self.ask:
        price = self.last
    else:
        price = self.midpoint()
else:
    price = self.last
```

so if this data is not available, then it means the symbol does not have an open interest or there is no last price. so that's why I make it a required field for most of the underlying related API calls.

**Comment by brndnmtthws** [comment]
See #524, I think that is the preferred behaviour in this case.

**Comment by junyuanz1** [comment]
okay, so if that's the case, then we should:

```
- buy_ticker = await self.ibkr.get_ticker_for_contract(position.contract)
+ buy_ticker = await self.ibkr.get_ticker_for_contract(position.contract, required_fields = [], optional_fields = [TickerField.MARKET_PRICE, TickerField.MIDPOINT])
```

**Pull request merged**
