### PR TITLE
issue 425 support per symbol dte configuration

### PR DESCRIPTION
**Pull request by noamagiv**
support DTE per symbol, same flow as target_delta. 
1. add new validation under symbol and symbol.right
2. create get_target_dte in util (as get_target_delta)
3. update find_eligible_contracts in portfolio_manager 

test with 
  [symbols.XLE]
  weight = 0.10
  delta = 0.3
  #write_threshold = 0.01
  dte = 80

  [symbols.BITO]
  weight = 0.15
  delta = 0.3

### CODE REVIEW

**Review by brndnmtthws — CHANGES_REQUESTED** [review]
This is a good start, and I appreciate the submission.

I think we need to update/document this in `thetagang.toml`, then we're good to go.

It's a bit confusing that we can specify `dte` separately for puts/calls, but `max_dte` is only per-symbol, so I think that should get sorted out at some point but it can be in a separate PR.

Ideally there we be a per-symbol value (like with `max_dte`) which applies to both puts and calls, and then an override for each contract type that takes precedence over everything else. That will be backward-compatible, and give enough flexibility to do whatever you want.

**Comment by noamagiv** [comment]
document change in toml.
you're right, DTE  and max DTE behavior should be aligned, I'll change it and commit to this PR.

**Comment by noamagiv** [comment]
document change in toml.
you're right, is dte and max DTE should behavior should be aligned, I'll change it and commit to this PR.

**Comment by brndnmtthws** [comment]
You need to fix the formatting issues, which you can do with the black tool. You can also [install the git hooks as noted here](https://github.com/brndnmtthws/thetagang/?tab=readme-ov-file#development). To run black manually, do `poetry install && poetry run black .`

**Review by brndnmtthws — APPROVED** [review]

**Comment by brndnmtthws** [comment]
You need to resolve the conflicts, which I think should be trivial, then we're good to go :shipit:

**Comment by noamagiv** [comment]
> You need to resolve the conflicts, which I think should be trivial, then we're good to go :shipit:

Which conflicts?

**Comment by brndnmtthws** [comment]
You need to either merge the `main` branch into your branch, or rebase your branch onto `main`. You can pull from `main` with `git pull https://github.com/brndnmtthws/thetagang.git main`.

GitHub provides two guides on how to do this if you're not familiar:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

**Comment by noamagiv** [comment]
Thanks, I appreciate you're patience! 
I've tried to rebase or merge and got this error : 

noam@TATPS:~/dev/thetagang$ git pull https://github.com/brndnmtthws/thetagang.git main merge
fatal: couldn't find remote ref merge

I synced my breach with main changes from github with sync fork and it updated my PR, I hope it's ok. 

It's strange, I followed the docs that you sent and I didn't saw any conflict error, just that main in ahead my branch so I just synced it.

**Pull request merged**
